<%@ Page Title="" Language="C#" MasterPageFile="~/master/Site1.Master" AutoEventWireup="true" CodeBehind="PayPalAccountConfigure.aspx.cs" Inherits="WebApplication1.pages.PayPalAccountConfigure" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="row">
        <div class="col-sm-1">
        </div>
        <div class="col-sm-10">
            <h2>Paypal data configuration</h2>
            <br>
            <div id="preview" runat="server"></div>
            <br>


            <%-- Table --%>
            <asp:GridView
                CssClass="table table-hover"
                ID="GridView1"
                runat="server"
                CellPadding="4"
                ForeColor="#333333"
                GridLines="None"
                SelectedRowStyle-BackColor="#888888"
                AutoGenerateColumns="False"
                AutoGenerateDeleteButton="True"
                AutoGenerateEditButton="True"
                DataKeyNames="paypal_id"
                DataSourceID="SqlDataSource1" ShowFooter="True">
                <Columns>

                    <%--Paypal ID--%>
                    <asp:TemplateField HeaderText="PayPal ID" SortExpression="paypal_id">
                        <EditItemTemplate>
                            <asp:Label ID="Label112" runat="server" Text='<%# Eval("paypal_id") %>'></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label312" runat="server" Text='<%# Bind("paypal_id") %>'></asp:Label>
                        </ItemTemplate>
                        <FooterTemplate>
                            <asp:LinkButton ValidationGroup="INSERT" ID="lbInsert" runat="server" OnClick="lbInsert_Click">
                                Insert
                            </asp:LinkButton>
                        </FooterTemplate>
                    </asp:TemplateField>

                    <%--Email--%>
                    <asp:TemplateField HeaderText="Email" SortExpression="email">
                        <EditItemTemplate>
                            <asp:TextBox
                                CssClass="form-control"
                                ID="TextBoxMail1"
                                runat="server"
                                Text='<%# Bind("email") %>'>
                            </asp:TextBox>
                            <asp:RequiredFieldValidator
                                ValidationGroup="UPDATE"
                                ForeColor="Red"
                                runat="server"
                                ID="RequiredFieldValidator54"
                                ControlToValidate="TextBoxMail1"
                                ErrorMessage="Please enter your email!" />
                            <asp:RegularExpressionValidator
                                ValidationGroup="UPDATE"
                                ForeColor="Red"
                                Display="Dynamic"
                                ControlToValidate="TextBoxMail1"
                                ID="RegularExpressionValidator62"
                                ValidationExpression="\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*"
                                runat="server"
                                ErrorMessage="The email format is not correct" />
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label412" runat="server" Text='<%# Bind("email") %>'></asp:Label>
                        </ItemTemplate>
                        <FooterTemplate>
                            <asp:TextBox CssClass="form-control" ID="TextBoxMail" runat="server" Text="">

                            </asp:TextBox>
                            <asp:RequiredFieldValidator
                                ValidationGroup="INSERT"
                                ForeColor="Red"
                                runat="server"
                                ID="RequiredFieldValidator5"
                                ControlToValidate="TextBoxMail"
                                ErrorMessage="Please enter your email!" />
                            <asp:RegularExpressionValidator
                                ValidationGroup="INSERT"
                                ForeColor="Red"
                                Display="Dynamic"
                                ControlToValidate="TextBoxMail"
                                ID="RegularExpressionValidator6"
                                ValidationExpression="\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*"
                                runat="server"
                                ErrorMessage="The email format is not correct" />
                        </FooterTemplate>
                    </asp:TemplateField>

                    <%--User Full Name--%>
                    <asp:TemplateField HeaderText="Full Name in IC" SortExpression="name">
                        <EditItemTemplate>
                            <asp:TextBox
                                CssClass="form-control"
                                ID="TextBox1"
                                runat="server"
                                Text='<%# Bind("name") %>'>
                            </asp:TextBox>
                            <asp:RequiredFieldValidator
                                ValidationGroup="UPDATE"
                                ForeColor="Red"
                                runat="server"
                                ID="RequiredFieldValidator3"
                                ControlToValidate="TextBox1"
                                ErrorMessage="Please enter your full name!" />
                            <asp:RegularExpressionValidator
                                ValidationGroup="UPDATE"
                                ForeColor="Red"
                                Display="Dynamic"
                                ControlToValidate="TextBox1"
                                ID="RegularExpressionValidator4"
                                ValidationExpression="[a-zA-Z ]{0,20}$"
                                runat="server"
                                ErrorMessage="The full name only accept max 20 word and must be character only" />
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label398" runat="server" Text='<%# Bind("name") %>'></asp:Label>
                        </ItemTemplate>
                        <FooterTemplate>
                            <asp:TextBox CssClass="form-control" ID="TextBoxFullName" runat="server" Text="">

                            </asp:TextBox>
                            <asp:RequiredFieldValidator
                                ValidationGroup="INSERT"
                                ForeColor="Red"
                                runat="server"
                                ID="RequiredFieldValidator31"
                                ControlToValidate="TextBoxFullName"
                                ErrorMessage="Please enter your first name!" />
                            <asp:RegularExpressionValidator
                                ValidationGroup="INSERT"
                                ForeColor="Red"
                                Display="Dynamic"
                                ControlToValidate="TextBoxFullName"
                                ID="RegularExpressionValidator42"
                                ValidationExpression="[a-zA-Z ]{0,20}$"
                                runat="server"
                                ErrorMessage="The first name only accept max 20 word and must be character only" />
                        </FooterTemplate>
                    </asp:TemplateField>

                    <%--Balancee--%>
                    <asp:TemplateField HeaderText="Balance" SortExpression="amount">
                        <EditItemTemplate>
                            <asp:TextBox
                                CssClass="form-control"
                                ID="TextBox2"
                                runat="server"
                                Text='<%# Bind("amount", "{0:0.00}") %>'>
                            </asp:TextBox>
                            <asp:RequiredFieldValidator
                                ValidationGroup="UPDATE"
                                ForeColor="Red"
                                runat="server"
                                ID="RequiredFieldValidator1"
                                ControlToValidate="TextBox2"
                                ErrorMessage="Please enter the balance!" />
                            <asp:RegularExpressionValidator
                                ValidationGroup="UPDATE"
                                ForeColor="Red"
                                Display="Dynamic"
                                ControlToValidate="TextBox2"
                                ID="RegularExpressionValidator11"
                                ValidationExpression="^\d{0,10}(\.\d{1,2})?$"
                                runat="server"
                                ErrorMessage="The balance is too large" />
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label4" runat="server" Text='<%# Bind("amount", "{0:0.00}") %>'></asp:Label>
                        </ItemTemplate>
                        <FooterTemplate>
                            <asp:TextBox CssClass="form-control" ID="TextBoxAmount" runat="server" Text="">

                            </asp:TextBox>
                            <asp:RequiredFieldValidator
                                ValidationGroup="INSERT"
                                ForeColor="Red"
                                runat="server"
                                ID="RequiredFieldValidator2"
                                ControlToValidate="TextBoxAmount"
                                ErrorMessage="Please enter the balance!" />
                            <asp:RegularExpressionValidator
                                ValidationGroup="INSERT"
                                ForeColor="Red"
                                Display="Dynamic"
                                ControlToValidate="TextBoxAmount"
                                ID="RegularExpressionValidator12"
                                ValidationExpression="^\d{0,10}(\.\d{1,2})?$"
                                runat="server"
                                ErrorMessage="The balance is too large" />
                        </FooterTemplate>
                    </asp:TemplateField>

                    <%--Password--%>
                    <asp:TemplateField HeaderText="Password" SortExpression="password">
                        <EditItemTemplate>
                            <asp:TextBox
                                CssClass="form-control"
                                ID="TextBox3"
                                runat="server"
                                Text='<%# Bind("password") %>'>
                            </asp:TextBox>
                            <asp:RequiredFieldValidator
                                ValidationGroup="UPDATE"
                                ForeColor="Red"
                                runat="server"
                                ID="RequiredFieldValidator61"
                                ControlToValidate="TextBox3"
                                ErrorMessage="Please enter your password!" />
                            <asp:RegularExpressionValidator
                                ValidationGroup="UPDATE"
                                ForeColor="Red"
                                Display="Dynamic"
                                ControlToValidate="TextBox3"
                                ID="RegularExpressionValidator21"
                                ValidationExpression="[a-zA-Z0-9]{8,50}$"
                                runat="server"
                                ErrorMessage="The password only accept 8 to 50 word and must be number or character" />
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label5" runat="server" Text='<%# Bind("password") %>'></asp:Label>
                        </ItemTemplate>
                        <FooterTemplate>
                            <asp:TextBox
                                CssClass="form-control"
                                ID="TextBoxPassword"
                                runat="server"
                                Text=""
                                TextMode="Password">
                            </asp:TextBox>
                            <asp:RequiredFieldValidator
                                ValidationGroup="INSERT"
                                ForeColor="Red"
                                runat="server"
                                ID="RequiredFieldValidator71"
                                ControlToValidate="TextBoxPassword"
                                ErrorMessage="Please reenter the password agian!" />
                            <asp:RegularExpressionValidator
                                ValidationGroup="INSERT"
                                ForeColor="Red"
                                Display="Dynamic"
                                ControlToValidate="TextBoxPassword"
                                ID="RegularExpressionValidator32"
                                ValidationExpression="[a-zA-Z0-9]{8,50}$"
                                runat="server"
                                ErrorMessage="The password only accept 8 to 50 word and must be number or character" />
                        </FooterTemplate>
                    </asp:TemplateField>

                </Columns>
                <SelectedRowStyle BackColor="#888888"></SelectedRowStyle>
            </asp:GridView>
            <asp:SqlDataSource
                ID="SqlDataSource1"
                runat="server"
                ConnectionString="<%$ ConnectionStrings:ConnectionString3 %>"
                DeleteCommand="DELETE FROM [PayPal] WHERE [paypal_id] = @paypal_id"
                InsertCommand="INSERT INTO [PayPal] ([paypal_id], [name], [email], [amount], [password]) VALUES (@paypal_id, @name, @email, @amount, @password)"
                SelectCommand="SELECT * FROM [PayPal]"
                UpdateCommand="UPDATE [PayPal] SET [name] = @name, [amount] = @amount, [email] = @email, [password] = @password WHERE [paypal_id] = @paypal_id">
                <DeleteParameters>
                    <asp:Parameter Name="paypal_id" Type="String" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="paypal_id" Type="String" />
                    <asp:Parameter Name="name" Type="String" />
                    <asp:Parameter Name="email" Type="String" />
                    <asp:Parameter Name="amount" Type="Decimal" />
                    <asp:Parameter Name="password" Type="String" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="email" Type="String" />
                    <asp:Parameter Name="name" Type="String" />
                    <asp:Parameter Name="amount" Type="Decimal" />
                    <asp:Parameter Name="password" Type="String" />
                    <asp:Parameter Name="paypal_id" Type="String" />
                </UpdateParameters>
            </asp:SqlDataSource>

        </div>
        <div class="col-sm-1">
        </div>
    </div>
</asp:Content>
