//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Art
    {
        public int art_id { get; set; }
        public int artist_id { get; set; }
        public byte[] image { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.DateTime> date_done { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    }
}
