//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitArt
    {
        public int bit_art_id { get; set; }
        public int art_id { get; set; }
        public int customer_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public string price { get; set; }
        public int payment_id { get; set; }
    }
}
