//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArtGalleryV2Entities : DbContext
    {
        public ArtGalleryV2Entities()
            : base("name=ArtGalleryV2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Art> Arts { get; set; }
        public virtual DbSet<BankTranfer> BankTranfers { get; set; }
        public virtual DbSet<BitArt> BitArts { get; set; }
        public virtual DbSet<Card> Cards { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }
        public virtual DbSet<PayPal> PayPals { get; set; }
        public virtual DbSet<PM_BankTranfer> PM_BankTranfer { get; set; }
        public virtual DbSet<PM_Card> PM_Card { get; set; }
        public virtual DbSet<ProductRelation> ProductRelations { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<PM_PayPal> PM_PayPal { get; set; }
        public virtual DbSet<ChangePassword> ChangePasswords { get; set; }
        public virtual DbSet<Page> Pages { get; set; }
    }
}
