//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int payment_id { get; set; }
        public int order_id { get; set; }
        public int payment_method_id { get; set; }
        public string status { get; set; }
        public Nullable<decimal> total_price { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
    }
}
