//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMethod
    {
        public int payment_method_id { get; set; }
        public int user_id { get; set; }
        public int payment_role_id { get; set; }
        public string payment_role { get; set; }
    }
}
