//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.model
{
    using System;
    
    public enum PaymentStatus : int
    {
        NotPaid = 78,
        Paid = 80,
        Cancled = 67,
        Refund = 82
    }
}
