//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int user_id { get; set; }
        public string user_email { get; set; }
        public string username { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string user_role { get; set; }
        public string phone_num { get; set; }
        public string gender { get; set; }
        public byte[] picture { get; set; }
        public string password { get; set; }
    }
}
